version: "3"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "12321:80"
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile

    environment:
      - REASONING_MODEL_PATH=http://192.168.100.231:11434
      - REASONING_MODEL_NAME=qwen2.5-coder:32b
      - REASONING_MODEL_PROVIDER=ollama
      - CODE_MODEL_PATH=http://192.168.100.201:8000/v1
      - CODE_MODEL_NAME=afsim-3b
      - CODE_MODEL_PROVIDER=openai

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
